- name: install common dependencies
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
     - jq
     - gcc
     - python3-pip
     - libffi-devel
     - openssl-devel
     - python3
     - python3-devel
     - yum-utils

- name: uninstall unnecessary packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
     - cockpit

- name: clean up yum.
  ansible.builtin.command: yum clean all
  changed_when: false
