---

- ansible.builtin.include_tasks: dependencies.yml
- ansible.builtin.include_tasks: yum.yml
- ansible.builtin.include_tasks: selinux.yml
  when: provider != "metal"

- ansible.builtin.include_tasks: upgrade.yml

- name: ensure lock directory is created
  ansible.builtin.file:
    path: /var/lock/subsys
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure that postfix is disabled
  ansible.builtin.service:
    name: postfix
    enabled: false
    state: stopped
  ignore_errors: yes

- name: ensure that kdump is disabled
  ansible.builtin.service:
    name: kdump
    enabled: false
    state: stopped
  ignore_errors: yes

- ansible.builtin.meta: flush_handlers
