---

- include_tasks: dependencies.yml
- include_tasks: yum.yml
- include_tasks: selinux.yml
- include_tasks: upgrade.yml

- name: ensure lock directory is created
  file: path=/var/lock/subsys state=directory owner=root group=root mode=0755

- name: ensure that postfix is disabled
  service: name=postfix enabled=no state=stopped
  ignore_errors: yes

- name: ensure that kdump is disabled
  service: name=kdump enabled=no state=stopped
  ignore_errors: yes

- meta: flush_handlers
