---

- name: install selinux dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libselinux
      - libselinux-utils
      - policycoreutils
      - python3-policycoreutils
      - policycoreutils-python-utils
      - selinux-policy-targeted
      - python3-libselinux

- name: enforce selinux
  selinux:
    policy: targeted
    state: enforcing
  notify:
  - bootstrap autorelabel
  - bootstrap reboot needed

- name: enforce selinux
  copy:
    src: files/selinux_config
    dest: /etc/selinux/config
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: selinux_config_t
    selevel: s0

- name: symlink /etc/sysconfig/selinux
  file:
    force: yes
    state: link
    src: /etc/selinux/config
    dest: /etc/sysconfig/selinux
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: selinux_config_t
    selevel: s0
