---

- name: upgrade kernel package
  yum:
    name: kernel
    state: latest
  when: provider is not defined or (provider is defined and provider != "ec2")
  notify:
  - bootstrap reboot needed

- name: upgrade all packages
  yum:
    name: "*"
    state: latest
    exclude: kernel
