---

- name: upgrade kernel package
  yum:
    name: kernel
    state: latest
  notify:
  - bootstrap reboot needed

- name: upgrade all packages
  yum:
    name: "*"
    state: latest
    exclude: kernel
