---
- name: bootstrap autorelabel
  ansible.builtin.file:
    path: /.autorelabel
    owner: root
    group: root
    state: touch
    mode: "0755"

- name: bootstrap reboot needed
  ansible.builtin.reboot:
    post_reboot_delay: "{{ bootstrap_reboot_delay | default(100) }}"
  when: provider != "vagrant"
